meta_params:
  # On-policy parameters
  n_rollout_steps: 2048
  n_epochs: 10
  num_mini_batch: 32

  # Network parameters
  lr: 0.0003
  adam_eps: 0.00001
  alpha: 0.99

  # Tunable parameters
  policy_clip_param: 0.2
  clip_policy_grad_norm: true

  # PPO parameters
  gamma: 0.99
  use_gae: true
  gae_lambda: 0.95
  entropy_coef: 0.0
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  clip_param: 0.2
  solver_linear_lr_decay: true
  opt_var_linear_lr_decay: false
  use_proper_time_limits: true